# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Blog.create([
  { :user_id => 1, :category => "Howto", :topic => "Getting Mercury Going", :excerpt => "Whatever", :article => "This is the story of getting mercury going.&nbsp;<div><br><div>So far... No love.&nbsp;</div><div><br></div><div>Maybe soon I will have a powerful editor that I can invoke from anywhere and it will be awesome and cool and newish.&nbsp;</div><div>Then I will be a real HTML 5 kinda guy.&nbsp;</div><div><b>Here's hoping!</b>\n\n</div><div><br></div><div><b>{:&gt;</b> Tom</div>\n</div>", :created_at => "2012-10-27 13:11:37", :updated_at => "2012-11-01 22:54:51", :featured => false },
  { :user_id => 1, :category => "Development", :topic => "First Thoughts", :excerpt => nil, :article => "<h3><span class=\"large-bold\"><span>My new article</span></span></h3><div>Boy this is nice and intuitive.</div><div>I love it I think.</div><div>Pretty sweet.</div><div><ul><li>Here's a point</li><li>And another</li><ul><li>A&nbsp;sub-point.</li><li>Now we are cooking.</li></ul></ul><div>Love it.</div></div><div><br></div>", :created_at => "2012-10-27 17:50:35", :updated_at => "2012-10-27 19:45:29", :featured => nil }
], :without_protection => true )



Mercury::Image.create([
  { :image_file_name => "2012-10-18-190452.jpg", :image_content_type => "image/jpeg", :image_file_size => 292543, :image_updated_at => "2012-10-27 18:15:32", :created_at => "2012-10-27 18:15:33", :updated_at => "2012-10-27 18:15:33" },
  { :image_file_name => "2012-10-18-190452.jpg", :image_content_type => "image/jpeg", :image_file_size => 292543, :image_updated_at => "2012-10-27 19:34:24", :created_at => "2012-10-27 19:34:24", :updated_at => "2012-10-27 19:34:24" },
  { :image_file_name => "2012-10-18-190452.jpg", :image_content_type => "image/jpeg", :image_file_size => 292543, :image_updated_at => "2012-10-27 19:43:05", :created_at => "2012-10-27 19:43:06", :updated_at => "2012-10-27 19:43:06" }
], :without_protection => true )



Participant.create([
  { :user_id => 1, :role_id => 1, :school_id => 1, :language_id => 1, :prereq => true, :accepted => 1, :theme => nil, :avatar => nil, :wallpaper => nil, :created_at => "2012-11-03 01:11:58", :updated_at => "2012-11-03 01:11:58" }
], :without_protection => true )



Role.create([
  { :rolename => "leader", :created_at => "2012-02-11 00:00:00", :updated_at => "2012-02-11 00:00:00" },
  { :rolename => "assistant", :created_at => "2012-02-11 00:00:00", :updated_at => "2012-02-11 00:00:00" },
  { :rolename => "staff", :created_at => "2012-02-11 00:00:00", :updated_at => "2012-02-11 00:00:00" },
  { :rolename => "student", :created_at => "2012-02-11 00:00:00", :updated_at => "2012-02-11 00:00:00" }
], :without_protection => true )



School.create([
  { :version_id => 1, :language_id => 1, :name => "Test School", :location => "Here", :prereqs => "Successful DTS", :start_date => "2012-11-03 01:28:00", :end_date => "2013-11-03 01:28:00", :mailing_address => "3 Mission Ln\r\nLakeside, MT\r\n59922", :tagline => "This is an awesome school", :description => "This is the test school.", :enrolement_type => true, :active => true, :timezone => "", :created_at => "2012-11-03 01:30:13", :updated_at => "2012-11-03 01:30:13" }
], :without_protection => true )



User.create([
  { :email => "tompossin@gmail.com", :encrypted_password => "$2a$10$e78DoQ3pXhQt62wkN26Ow.8f8b6BO52cuybpAYHKVfMQI3gLydjl2", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 2, :current_sign_in_at => "2012-11-03 01:21:14", :last_sign_in_at => "2012-11-03 01:20:02", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :confirmation_token => nil, :confirmed_at => nil, :confirmation_sent_at => nil, :unconfirmed_email => nil, :failed_attempts => 0, :unlock_token => nil, :locked_at => nil, :authentication_token => nil, :created_at => "2012-11-03 01:20:02", :updated_at => "2012-11-03 01:21:14", :firstname => "Tom", :lastname => "Possin", :phone => "406-844-1667", :address => "3 Mission Ln\r\nLakeside, MT\r\n59922" },
  { :email => "tompossin@studyworx.info", :encrypted_password => "$2a$10$VBFjCem.BI59CU7ojq3bgOPjhjqPJhmgekP37Vc796SWz2hBqGWS6", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 1, :current_sign_in_at => "2012-11-03 01:20:52", :last_sign_in_at => "2012-11-03 01:20:52", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :confirmation_token => nil, :confirmed_at => nil, :confirmation_sent_at => nil, :unconfirmed_email => nil, :failed_attempts => 0, :unlock_token => nil, :locked_at => nil, :authentication_token => nil, :created_at => "2012-11-03 01:20:52", :updated_at => "2012-11-03 01:20:52", :firstname => "Buster", :lastname => "Bigtime", :phone => "", :address => "Here\r\nLakeside, MT" }
], :without_protection => true )



UserAdmin.create([
  { :user_id => 1, :level => 3, :created_at => "2012-10-25 19:23:02", :updated_at => "2012-10-25 19:23:02" },
  { :user_id => nil, :level => nil, :created_at => "2012-10-25 23:07:56", :updated_at => "2012-10-25 23:07:56" }
], :without_protection => true )


